### ISSUE TITLE
Can't bind to 'Highcharts' since it isn't a known property of 'highcharts-chart'.

### ISSUE THREAD

**Issue by johndacost** [highcharts/highcharts-angular#120]
> For general tech support, please see www.highcharts.com/support.
> Please report only issues about `highcharts-angular` wrapper or content of this repository.
> For general issues with Highcharts and TypeScript the correct repository to report such issues is [main Highcharts repository](https://github.com/highcharts/highcharts/issues).

### Describe the bug
```
Uncaught Error: Template parse errors:
Can't bind to 'Highcharts' since it isn't a known property of 'highcharts-chart'.
1. If 'highcharts-chart' is an Angular component and it has 'Highcharts' input, then verify that it is part of this module.
2. If 'highcharts-chart' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
```

### Expected behavior
I'm trying to run this sample 

...
//app.module.ts
import { HighchartsChartModule } from 'highcharts-angular';

@NgModule({
  imports: [
    ...
    HighchartsChartModule

```
 //some-component.ts
  import * as Highcharts from 'highcharts';
  Highcharts = Highcharts;
  chartOptions = {
    series: [{
      data: [1, 2, 3]
    }]
  };
```
 //some-component.html
`<highcharts-chart [Highcharts]="Highcharts" [options]="chartOptions" style="width: 100%; height: 400px; display: block;"></highcharts-chart>`

### Setup used
 - NodeJS version 10.15.0
 - Angular version 6.1.4
 - TypeScript version ~2.7.2
 - highcharts version ^7.0.3
 - highcharts-angular version ^2.4.0

**Comment by KacperMadej** [comment]
Hi @johndacost 

Have your tried using a different name for the imported Highcharts in the `some-component.ts`? This should resolve the problem with already taken name.

**Comment by johndacost** [comment]
@KacperMadej 
I tried to change but still not working 

```
import * as __Highcharts from 'highcharts';

@Component({
  selector: 'measured-cote-table',
  templateUrl: './measured-cote-table.component.html',
  styleUrls: ['./measured-cote-table.component.scss']
})
export class MeasuredCoteTableComponent implements OnInit {
  ...
  Highcharts = __Highcharts;
  chartOptions = {
    series: [{
      data: [1, 2, 3]
    }]
  };
  ....
```

I got this on the console : 

```
compiler.js:1016 Uncaught Error: Template parse errors:
Can't bind to 'Highcharts' since it isn't a known property of 'highcharts-chart'.
1. If 'highcharts-chart' is an Angular component and it has 'Highcharts' input, then verify that it is part of this module.
2. If 'highcharts-chart' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
      </td>
      <td *ngIf="isShowGraph">
        <highcharts-chart [ERROR ->][Highcharts]="Highcharts" [options]="chartOptions" style="width: 100%; height: 400px; display: block;"): ng:///ViewModule/MeasuredCoteTableComponent.html@40:26
Can't bind to 'options' since it isn't a known property of 'highcharts-chart'.
```

It's look like the module is not imported correctly...

**Comment by KacperMadej** [comment]
The component has `Highcharts` input defined - https://github.com/highcharts/highcharts-angular/blob/master/highcharts-angular/src/lib/highcharts-chart.component.ts#L9

Maybe this import `import { HighchartsChartModule } from 'highcharts-angular';` is problematic. Have you added [it to imports](https://github.com/highcharts/highcharts-angular/blob/master/src/app/app.module.ts#L16) ?

Could you recreate the problem in a simple app or a live demo?

**Comment by johndacost** [comment]
Yes, I added it to imports and I tried with an example live on StackBlitz.io and it works.

But in my case I have many import in the app.module.ts... do you think module order matter ? 

Saddly, I'm unable to reproduce this online...

Here a snapshot of my app.module.ts 
```

import { HighchartsChartModule } from 'highcharts-angular';
import { FormsModule } from '@angular/forms';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HighchartsChartModule,
    BrowserAnimationsModule,
    AppRoutingModule,
    HttpClientModule,
    ViewModule,
    StoreModule.forRoot(reducer),
    StoreDevtoolsModule.instrument(),
    EffectsModule.forRoot([
      LoginEffect,
      UserEffect,
      MachineEffect,
      LogEffect,
      MachineUserSwitchEffect,
      WorkshopEffect,
      AestheticCriterionEffect,
      ControlPlanEffect,
      ControlRangeEffect,
      ArticleEffect,
      ControlMachineStartEffect,
      MachineControlArticleEffect,
      MachineUserSwitchEffect,
      SettingEffect,
    ]),
    HttpModule,
    HttpClientModule,
    AuthenticationModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: (createTranslateLoader),
        deps: [HttpClient]
      }
    }),
  ],
  providers: [
    httpInterceptorProviders,
```

**Comment by KacperMadej** [comment]
@johndacost 
I doubt that order matters - maybe some elements just being loaded somehow alter environment. You could try debugging by removing elements one by one to get a minimal demo that fails.

The error shows on the first input, so maybe all of them are not available - to confirm that you could change order of the inputs in the component usage (mentioned in the error message: `<highcharts-chart [ERROR ->][Highcharts]="Highcharts" [options]="chartOptions" style= ...`). Maybe all inputs are not assigned for some reason. If yes, then probably environment is changed in a way that prevents inputs from being defined in the component file and should be loaded differently. With a minimal demo it should be possible to track how working components are defining their inputs.

I could try to help with debugging if you could provide an app (with steps how to run) - preferably minimal.

**Comment by Alejandromvg** [comment]
I have the same error:

ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'Highcharts' since it isn't a known property of 'highcharts-chart'.

https://pastebin.com/anQBUFNf

I'm working with IONIC 4:

"angular": "^7.2.2",
"highcharts": "^7.0.3",
"highcharts-angular": "^2.4.0",

**Comment by smasithick** [comment]
Hi @KacperMadej and @johndacost ,

Here's StackBlitz link with the basic Highcharts sample.

[https://stackblitz.com/edit/highcharts-sample](url)

It's working perfectly. But, when we do the same in VS Code, I'm getting the same error.

`core.js:15713 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'Highcharts' since it isn't a known property of 'highcharts-chart'.
1. If 'highcharts-chart' is an Angular component and it has 'Highcharts' input, then verify that it is part of this module.
2. If 'highcharts-chart' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        <div class="card-body">
          <div class="chart-area">
            <highcharts-chart [ERROR ->][Highcharts]="highcharts" [options]="chartOptions" style="width: 100%; height: 400px; display: block;"): `

These are my dependencies...

"@angular/animations": "^7.2.4",
    "@angular/common": "^7.2.4",
    "@angular/compiler": "^7.2.4",
    "@angular/core": "^7.2.4",
    "@angular/forms": "^7.2.4",
    "@angular/http": "^7.2.4",
    "@angular/platform-browser": "^7.2.4",
    "@angular/platform-browser-dynamic": "^7.2.4",
    "@angular/platform-server": "^7.2.4",
    "@angular/router": "^7.2.4",
    "core-js": "^2.6.4",
    "highcharts": ">=6.0.0",
    "highcharts-angular": "^2.4.0",
    "typescript": "^3.2.4"

Node - v10.15.0

**Comment by KacperMadej** [comment]
@smasithick 
> But, when we do the same in VS Code, I'm getting the same error.

Please create the app package that could be run and build for debugging and testing.
This repository is also a demo and it works fine as far as I can test. Maybe you could edit that demo to show the problem and PR a branch with the code? Alternatively anything that would allow us to recreate the problem will be great.

@Alejandromvg 
Please create a live demo or post a zipped app that could be build for testing and debugging. I'm unable to debug the code based only on the error messages that you have provided so far.

**Comment by Alejandromvg** [comment]
I have the solution:

I am working in IONIC 4.

The new update works with angular 7, angular 7 change somethings like the imports. Now we have module.ts in every page:

src
---app.module.ts    => Here we imports everything, and we have the error. 
                                     **Can't bind to 'Highcharts' since it isn't a known property of 'highcharts-chart'.**
--app.component.ts
--app.component.spec.ts
--app.component.html
--app-routing.module.ts
--home
  --home.page.ts
  --home.page.spec.ts
  --home.page.scss
  --home.page.html
  --home.module.ts  => Here is we have to import now, and works.

Good look.

Pd: sorry for my english.

**Comment by johndacost** [comment]
@KacperMadej and @smasithick I found where was my problem....


I noticed that the graph only work if I did it from the `app.component.ts / html`. But in our project we have an `outlet-router`, `view.module.ts` (who contain all my components)  and an `app-routing.module.ts` and I forgot to import the HighchartsChartModule in the `view.module.ts`

**Comment by hheexx** [comment]
Same problem here.
I have app with multiple modules and I have to import highcharts to a module that includes a page I want to use highcharts on.

This should not be like that by design right ?

**Comment by KacperMadej** [comment]
Hi @hheexx 

You could try with the two suggestion from the 2 comments over your previous one.
Your description is too vague, so I cannot suggest anything more precise.
Please create a live demo or a share an app that could be used to recreate the problem.

**Comment by smasithick** [comment]
> Hi @KacperMadej and @johndacost ,
> 
> Here's StackBlitz link with the basic Highcharts sample.
> 
> https://stackblitz.com/edit/highcharts-sample
> 
> It's working perfectly. But, when we do the same in VS Code, I'm getting the same error.
> 
> `core.js:15713 ERROR Error: Uncaught (in promise): Error: Template parse errors:
> Can't bind to 'Highcharts' since it isn't a known property of 'highcharts-chart'.
> 
> 1. If 'highcharts-chart' is an Angular component and it has 'Highcharts' input, then verify that it is part of this module.
> 2. If 'highcharts-chart' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
> 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
>    
>    
>    <highcharts-chart [ERROR ->][Highcharts]="highcharts" [options]="chartOptions" style="width: 100%; height: 400px; display: block;"): `
> 
> These are my dependencies...
> 
> "@angular/animations": "^7.2.4",
> "@angular/common": "^7.2.4",
> "@angular/compiler": "^7.2.4",
> "@angular/core": "^7.2.4",
> "@angular/forms": "^7.2.4",
> "@angular/http": "^7.2.4",
> "@angular/platform-browser": "^7.2.4",
> "@angular/platform-browser-dynamic": "^7.2.4",
> "@angular/platform-server": "^7.2.4",
> "@angular/router": "^7.2.4",
> "core-js": "^2.6.4",
> "highcharts": ">=6.0.0",
> "highcharts-angular": "^2.4.0",
> "typescript": "^3.2.4"
> 
> Node - v10.15.0

A solution in this link works perfectly :)

https://github.com/highcharts/highcharts-angular/issues/120#issuecomment-468532235

We can close this issue thread. @KacperMadej

**Comment by KacperMadej** [comment]
Great, thank you.
Closing the issue.

**Comment by shravansofts** [comment]
We are facing the same issue while running ng test.
I had included the module in the same component's module still test is not working.
Why can't you provide a sample spec file for the sample you had given??

**Comment by POONGOTHAIELUMALIA** [comment]
Hi,

I am also getting the same error.

am working in Angular 8

**Uncaught Error: Template parse errors:
Can't bind to 'Highcharts' since it isn't a known property of 'highcharts-chart'.
1. If 'highcharts-chart' is an Angular component and it has 'Highcharts' input, then verify that it is part of this module.


2. If 'highcharts-chart' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  <div>
    <highcharts-chart id="container"
                      [ERROR ->][Highcharts]="Highcharts"
                      [constructorType]="chartConstructor"
              "): ng:///AppModule/AppComponent.html@3:22
Can't bind to 'constructorType' since it isn't a known property of 'highcharts-chart'.**

**Comment by KacperMadej** [comment]
Please try the suggested solution(s) in the above comments.
If this doesn't help then please create a minimal live demo showing the problem - an online sandbox will be fine if you are able to recreate the problem there, or you could provide a zipped app with instructions for how to run it and recreate the problem.

**Comment by mateuszkornecki** [comment]
The issue is also related to the [Angular Language Service](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template), disabling the extension or restarting it might fix the problem.

**Comment by 10YearsDiary** [comment]
I had same issue, and resolved by followed code int the module config:

import { HighchartsChartModule } from 'highcharts-angular';
...
  imports: [
    ...,
    HighchartsChartModule,
...

**Comment by hibanebli** [comment]
> I have the solution:
> 
> I am working in IONIC 4.
> 
> The new update works with angular 7, angular 7 change somethings like the imports. Now we have module.ts in every page:
> 
> ```
> src
> ---app.module.ts    => Here we imports everything, and we have the error. 
>                                      Can't bind to 'Highcharts' since it isn't a known property of 'highcharts-chart'.
> --app.component.ts
> --app.component.spec.ts
> --app.component.html
> --app-routing.module.ts
> --home
>   --home.page.ts
>   --home.page.spec.ts
>   --home.page.scss
>   --home.page.html
>   --home.module.ts  => Here is we have to import now, and works.
> ```
> 
> Good luck.
> 
> Pd: sorry for my english.

Sorry can you explain more your solution ? what are the imports we add in home.module.ts

**Comment by mateuszkornecki** [comment]
It was about the `HighchartsChartModule`.

```javascript
import { HighchartsChartModule } from 'highcharts-angular';
...
imports: [
...,
HighchartsChartModule,
...
```

**Comment by abhiabhisheik646** [comment]
### component.ts


import {Component, OnInit, ViewChild} from '@angular/core';
import { MatTableDataSource} from '@angular/material/table';
import * as Highcharts from "highcharts";

export class PatientdetailsComponent implements OnInit {

  Highcharts: typeof Highcharts = Highcharts;

chartOptions: Highcharts.Options = {
    series: [
      {
        type: "line",
        data: [1, 2, 3, 4, 5]
      }
    ]
  };

}

#### app.module.ts

 import { HighchartsChartModule } from 'highcharts-angular';

import:[HighchartsChartModule]

Error:
1. If 'highcharts-chart' is an Angular component and it has 'Highcharts' input, then verify that it is part of this module.
    2. If 'highcharts-chart' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 
    3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

**Comment by ayushshrestha** [comment]
@abhiabhisheik646 
https://github.com/highcharts/highcharts-angular/issues/120#issuecomment-468532235

please try this or if this work please let me know too :)
