### ISSUE TITLE
Not compatible with Angular 6.0.0

### ISSUE THREAD

**Issue by kilatib** [highcharts/highcharts-angular#29]
We have just upgrade to angular6  and have this issue 
```

chunk {vendor} vendor.js, vendor.js.map (vendor) 325 kB [initial] [rendered]

ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/highcharts-angular/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

ℹ ｢wdm｣: Failed to compile.
```

```
Angular CLI: 6.0.1
Node: 9.11.1
OS: darwin x64
Angular: 6.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.13
@angular-devkit/build-angular     0.5.13
@angular-devkit/build-optimizer   0.5.13
@angular-devkit/core              0.5.13
@angular-devkit/schematics        0.6.1 (cli-only)
@angular/cli                      <error>
@ngtools/webpack                  6.0.0-rc.11
@schematics/angular               0.6.1 (cli-only)
@schematics/update                0.6.1 (cli-only)
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

**Comment by sebastianbochan** [comment]
Hi @kilatib 
Thank you for the reporting.

@KacperMadej any comments?

**Comment by kilatib** [comment]
Hi, @KacperMadej

Yes, it was released 11 days ago and looks pretty stable. 
If you would not wrap each angular version it would not cost a lot time just simple edit in `ng_dev_mode.d.ts`, otherwise your will have a problem with migration rxjs to 6 version.

**Comment by jonathan-bird** [comment]
Highcharts is one of the main plugins I'm using on one of my projects and would love this available on Angular 6.x

**Comment by jonathan-bird** [comment]
Is there a possibility of this being fixed soon @KacperMadej? Seems to only be that one ngDevMode error:

```
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/highcharts-angular/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/highcharts-angular/src/app/app.component.ts(7,31): error TS2497: Module '"/Users/jonathanbird/Projects/rumbles/rumbles-angular/node_modules/@types/highcharts/modules/exporting"' resolves to a non-module entity and cannot be imported using this construct.
node_modules/highcharts-angular/src/app/app.component.ts(10,1): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/Users/jonathanbird/Projects/rumbles/rumbles-angular/node_modules/@types/highcharts/modul...' has no compatible call signatures.
```

**Comment by mkdudeja** [comment]
Hi All,

Worked on converting this package to AOT & angular 6 compatible. Its built using Angular 6's library feature. Ideally, it should work with earlier versions of Angular too,

Following is the link to same.
https://www.npmjs.com/package/angular-highcharts-chart

Underlying options & usage guide remains the same.

Thanks

**Comment by envynoiz** [comment]
Any update on this? I appreciate the work of @mkdudeja but I really need the official one, I think it is necessary to update the wrapper when a new version of Angular is released or at least test it in order to verify the proper functionality.

**Comment by mkdudeja** [comment]
@envynoiz thanks for appreciation...

Hower, You can use the library as the core remains the same as official. Its just the wrapper on top of that to make it AOT & Angular V6 Compatible.

**Comment by ngehlert** [comment]
any updates on this task? This task is already 1,5 month old and Highcharts is currently still not usable with Angular 6. Any updates if this will be addressed or is this this repo no longer supported?

**Comment by KacperMadej** [comment]
This will be resolved within next 2-3 weeks.

**Comment by gregjacobs** [comment]
@ngehlert Adding the library build should fix this for you. Make sure to install 2.0.0 which @KacperMadej just released this morning

**Comment by KyleW** [comment]
I'm on highcharts-angular 2.02 and I'm still seeing this error when I build using Angular 6 in production mode (aot, minification, etc.).

**Comment by gregjacobs** [comment]
@KyleW The error that you're getting is telling you exactly what is wrong. Follow the setup instructions in the readme for 2.0 (this was the reason for the 1.x->2.x major version change: the setup is now different). In your `app.module.ts` file, remove `HighchartsComponent` from your `declarations` array, and add `HighchartsModule` to your `imports` array instead

**Comment by KyleW** [comment]
Yep. That did it. Thank you!

**Comment by gregjacobs** [comment]
@KyleW Ah good to hear! Happy coding :)

**Comment by gvaartjes** [comment]
@gregjacobs Thanks for helping out :)

**Comment by urvashimehra** [comment]
> Hey @KyleW, the error that you're getting is actually telling you what's wrong. Make sure to follow the setup instructions in the readme for 2.0 (this was the reason for the 1.x->2.x major version change: the setup is now different). In your `app.module.ts` file, remove `HighchartsComponent` from your `declarations` array, and add `HighchartsModule` to your `imports` array instead

can you please explain
